### ISSUE TITLE
Use python tests

### ISSUE THREAD

**Issue by DurgNomis-drol** [DurgNomis-drol/mytoyota#1]
**Describe the solution you'd like**

Use python tests to make the module robust.

Help wanted as I'm still very new to write code.

**Comment by DurgNomis-drol** [comment]
UPDATE:

Adding `conftest.py` to the repo root solves the issue. 🤔

**Comment by joro75** [comment]
An intermediate update regarding the progress of adding unittests:
A lot of unittests have been added in the past few days. The biggest part of the code is covered now by the unittests (also when #84 is being merged).
I also did run `pytest-cov` with these unittests and the current coverage is above 75%. 
Most of the lines that are not covered yet, are exceptions and sanity checks. The plan is to also add checks for those lines.

**Comment by joro75** [comment]
I have added more unittests today, and also checked the coverage reports of that. 
The total coverage (excluding the `controller.py`) should now be very close to 100%. 

One last thing I would like to suggest, is to link the coverage results of the unittests to the [codecov.io](https://about.codecov.io/) website, so we can easily check the coverage percentage, and also see which lines are not tested.

@DurgNomis-drol If you agree, can you create a codecov.io account for this repository?  (also see: https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/ )

I already have a github actions yml workflow available that can be merged into the existing workflows, so you don't have to do that, I can provide another PR for that.

**Comment by DurgNomis-drol** [comment]
@joro75 Awesome work you are doing!

I am all for adding codecov.io for this package. Give me a couple of days to get it setup, and I will then ping you for that awesome workflow you have ready. 🚀 😃

**Comment by DurgNomis-drol** [comment]
I have linked my account with codecov.io and made an initial upload from command line.  It seems that we don't need a token when we run the Github Action, so it should be straight forward 🚀

**Comment by joro75** [comment]
Yeah!! 😊😊 
I'm satisfied with the current status and the availability of the unittests in the mytoyota library. I will close this issue now. Also with the latest integration (See: #146) with the reporting of the coverage on Codecov.io, we do have a good implementation of the unittests. 

We of course still have to extend and add unittests for for new code and future code changes, but it at least we now have a good base to be able to close this issue.

**Comment by joro75** [comment]
Some additional information (also see: #147): I also added a codecov.yml file to the root directory to modify the default behaviour of the codecov.io integration. With the modified settings, the coverage will only show a failing coverage if it the default is more than 2% down. But still it will be possible to merge the PR at that moment.

**Comment by DurgNomis-drol** [comment]
Good idea, see my approval and comment on the PR 😊
