### ISSUE TITLE
mytoyota 0.7.4 dependency requierement error

### ISSUE THREAD

**Issue by saintfrater** [DurgNomis-drol/mytoyota#104]
**Describe the bug**
I'm trying to use MyToyota Connected Services and it's requiere mytoyota 0.7.4, so I've tryed to install it:

I cannot install the package (either via pip and webinterface), get 

```
mytoyota 0.7.4 requires httpx<0.19.0,>=0.18.1, but you have httpx 0.19.0 which is incompatible.
```

**To Reproduce**
upgrade python3.8 .11 (Debian version)

**Expected behavior**
working with latest httpx version (0.19.0)

**Screenshots**
N/A

**Additional context**

**Comment by DurgNomis-drol** [comment]
Good catch! 😃

**Comment by DurgNomis-drol** [comment]
Will see if I have time tomorrow to push a quick fix

**Comment by DurgNomis-drol** [comment]
If you are using the Home Assistant integration, I will publish a new version shortly, hoping to get another PR in, but if that drags out, I will an update with out it. 😃

**Comment by DurgNomis-drol** [comment]
A new version of the integration have just been released. 😃
