### ISSUE TITLE
Unlock/Lock Functions?

### ISSUE THREAD

**Issue by xpnewmedia** [DurgNomis-drol/mytoyota#119]
**Is your feature request related to a problem? Please describe.**
Am I able to lock and unlock my compatible vehicles using this API.
In addition to start and stop functions?

**Describe the solution you'd like**
I want to be able to track my vehicles and unlock or lock the doors when necessary.

I also want to start and safely stop my vehicle using the API.
**Describe alternatives you've considered**

**Additional context**

**Comment by DurgNomis-drol** [comment]
Can you do it in the MyT app?

**Comment by DurgNomis-drol** [comment]
To clarify my question, we can only implement features that exists in the app already. So the both the start/stop and lock/unlock feature has to be in the app for us the be able to do this 😊

**Comment by tijunoi** [comment]
@DurgNomis-drol At least in Spain, there is door lock/unlock functionality in the app as well as HVAC on/off (no temp adjust for my car though)

**Comment by joro75** [comment]
That is very interesting, as we cannot or do not know how  to remote lock/unlock the car from the MyT app. 
* Can you share a screenshot on how this can be done in the MyT app?
* Which version of the MyT app are you using?
* Which Toyota model do you own? Does it have special options that could cause that it is remote lockable?

Thanks!

**Comment by tijunoi** [comment]
> * Which version of the MyT app are you using?
iOS 4.10.0 (494). Although the feature is not new, already available last year.
> * Which Toyota model do you own? Does it have special options that could cause that it is remote lockable?
I have a Toyota Yaris Cross produced Sep 2021. AFAIK this is available to 2019-2020 Corolls, 2021-2022 Yaris, RAV4. Yaris Cross and Aygo X also have climate control (only on/off).

[This](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwinsKiTl_v2AhXLz4UKHZszDgUQFnoECCEQAQ&url=https%3A%2F%2Fwww.toyota-europe.com%2Fdownload%2Fcms%2Feuen%2FMyT%2520App%2520REMOTE%2520CONTROLS%2520CLIMATE%2520CONTROL%2520YARIS%2520CROSS%2520AYGO%2520CROSS_tcm-11-2409612.pdf&usg=AOvVaw13y8FC2PgwDBHbAXX3FeQ9) is the only info I could find.
> * Can you share a screenshot on how this can be done in the MyT app?

![IMG_6105](https://user-images.githubusercontent.com/8004985/161622756-439543d6-136f-4f25-9aff-06576492d151.jpeg)
![IMG_6106](https://user-images.githubusercontent.com/8004985/161622861-792571e2-ad1d-4da2-b83f-ecdf91285cfa.PNG)
![IMG_6107](https://user-images.githubusercontent.com/8004985/161622915-6afbe79c-622a-4e29-915a-34c5278a676e.PNG)

I tried intercepting the request via Proxyman to see the endpoint and payload for both lock/unlock and climate, but the app uses SSL pinning so I could not manage to do it. Can I assist somehow? I also have an Android device.

**Comment by joro75** [comment]
@tijunoi : Thanks for providing the requested information. It is very interesting!
I wasn't aware that this is possible. The problem now is that we have to find the correct URL/API call to also do this from the mytoyota library. I'm not sure how we can arrange that....

**Comment by DurgNomis-drol** [comment]
@joro75 You should be able to find the endpoint (URL) in the android app if you decompile it

**Comment by joro75** [comment]
I also found the 'official' documentation of Toyota that describes the Remote Lock/Unlock feature. It is available at: https://www.toyota-europe.com/download/cms/euen/MyT%20App%20DOOR%20LOCK%20UNLOCK_tcm-11-2409615.pdf

It seems to be available on the models:
* Yaris Cross
* Aygo X
* Yaris Model Year 21
* Toyota bZ4X
With the remark: Remote control features depend on local grade and specific OE options required.

**Comment by sebas00** [comment]
@tijunoi did you ever get around to code it? If not would you have the endpoint and request body specs documented somewhere?

**Comment by apmechev** [comment]
@tijunoi, do you have the endpoint/body handy? I'm interesting in implementing this

**Comment by DurgNomis-drol** [comment]
@joro75 should we wait a bit before we release a new version of the lib, so we can get a couple of people to test it, or should we just send it? 😃

**Comment by joro75** [comment]
@DurgNomis-drol I do no think that a lot of people will use the new unlock/lock function before it is released. If they want to do that, they already have to download and install the trunk version in some way.
In my opinion we can release this version, so it will be easier  for a lot of them to just update to the new library (using the pip installer). If there are problems we can provide a small fix-update. 

I do not expect a lot of problems, and I also have tested it with my vehicle (which doesn't support it). 
The only outstanding issue is that there is no good way to determine if  remote lock/unlock is supported by a vehicle. At this moment the end-user has to know for their  own vehicle  if it  is  supported, and otherwise  an exception is raised.
