### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by vanstinator** [DurgNomis-drol/mytoyota#123]
I'm spinning up to contribute to the NA version of this project and realized there's not a great place to come together and chat in regards to reverse engineering and whatnot. To that end I'm setting up a discord server for both the NA and EU projects so we can collaborate and work together.

Feel free to join

discord.gg/mFHJYew658

**Comment by vanstinator** [comment]
I'll admin repo owners and maintainers

**Comment by DurgNomis-drol** [comment]
I prefer to keep important discussion here on GitHub. It will make it easier for everyone to find all the things we figure out if it is kept in one place. 😀

**Comment by joro75** [comment]
I agree with DurgNomis-drol. It probably will have more benefits if we keep all the information and discussion on a single location (on GitHub).

**Comment by vanstinator** [comment]
The NA group is already using Discord and will probably continue to do so. Just thought I'd throw out the invite in case you guys wanted to collaborate and whatnot.
