### ISSUE TITLE
Ability to determine the version of the mytoyota library in code

### ISSUE THREAD

**Issue by joro75** [DurgNomis-drol/mytoyota#129]
- **Is your feature request related to a problem? Please describe.**
In my domoticz plugin, the mytoyota library is used, however I am not sure if the end-user who is using the domoticz plugin also has installed the latest mytoyota library, because it is installed using 'pip', and the end-user can update the domoticz plugin without updating the pip libraries.

- **Describe the solution you'd like**
I thus would like to have a possibility that my python code (which is using the mytoyota library) is able to check the version of the actually used/installed mytoyota library. In case that it is too old, the python plugin can then take appropiate actions, like rasising a warning.
Best implementation seems to follow [PEP 396](https://www.python.org/dev/peps/pep-0396/) which requires that a __version__ attribute is included. This also seems to be used by a lot of other python libraries.

- **Describe alternatives you've considered**
Checking and performing pip3 queries from an embedded commandline is ofcourse possible, but more complicated, and too heavy.

- **Additional context**
I will continue to suggest a code change, and will provide a PR later.

**Comment by joro75** [comment]
After some research I plan to use the suggested implementation at: https://github.com/python-poetry/poetry/issues/144#issuecomment-623927302

**Comment by DurgNomis-drol** [comment]
Sounds like you have found a good solution 👍
