### ISSUE TITLE
South Africa

### ISSUE THREAD

**Issue by chriscc12345** [DurgNomis-drol/mytoyota#170]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joro75** [comment]
Hi @chriscc12345 ,

I checked the 'MyToyota' page for South Africa. It is available on: https://www.toyota.co.za/my-toyota/overview
It is referring to the Android 'MyToyota' app on https://play.google.com/store/apps/details?id=com.eliance.toyotamobile&hl=en. 

This however seems to have a different layout, and different settings than the 'MyT' app (https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=en) that this [mytoyota](https://github.com/DurgNomis-drol/mytoyota) library is using. I'm also afraid that the backend toyota servers are also different. 

Did you already try to use the small example program (as shown on https://github.com/DurgNomis-drol/mytoyota ) to retrieve the information of your vehicle? Is that working, or isn't it?

**Comment by chriscc12345** [comment]
Hi I am asking for support on  Home Assistant 
![image](https://user-images.githubusercontent.com/60073902/185465050-fbe11738-ef44-4301-a894-4b162322c71f.png)

**Comment by joro75** [comment]
@chriscc12345 For the Toyota plugin in Home Assistent, it is better to raise your question in the [corresponding repository](https://github.com/DurgNomis-drol/ha_toyota).

On the other hand, I do have to admit that the Toyota Plugin in Home Assistent is also using this mytoyota library to retrieve the actual information. If support for South Africa is possible in this mytoyota library, it will be fairly easy to also support the South Africa region in the toyota plugin in Home Assistent.

Please see my previous comment in this thread. 

> I checked the 'MyToyota' page for South Africa. It is available on: https://www.toyota.co.za/my-toyota/overview It is referring to the Android 'MyToyota' app on https://play.google.com/store/apps/details?id=com.eliance.toyotamobile&hl=en.
> 
> This however seems to have a different layout, and different settings than the 'MyT' app (https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=en) that this [mytoyota](https://github.com/DurgNomis-drol/mytoyota) library is using. I'm also afraid that the backend toyota servers are also different.
> 
> Did you already try to use the small example program (as shown on https://github.com/DurgNomis-drol/mytoyota ) to retrieve the information of your vehicle? Is that working, or isn't it?

Did you already try to use the small example program, to retrieve the information of your vehicle? Is that working??
If it isn't working, please provide us with detailed feedback of error message and so on, so we can continue to investigate if we can add support.
Thanks!

**Comment by samgangiah** [comment]
The MyToyota app for South Africa, doesn't seem to use a password, but rather it uses a one time pin. Well it does for me; not sure about others.

I tried using the example program, but it seems to point to Europe servers by default and my user name does not work on Europe servers, also I have no password, as explain above.

**Comment by DurgNomis-drol** [comment]
Toyota Connected Services is very different for each region. I believe that the system is build by different Toyota partners and therefor it is incompatible with each other. When I set out to build this over a year and a half ago, I thought I could make a global library. But this is not possible as each regions app does not share anything in common with each other. 

You can only hope that some on in the future creates a library or you can take the journey yourself 😃

**Comment by joro75** [comment]
Also please see https://github.com/DurgNomis-drol/mytoyota/discussions/207 for a more detailed explanation.
