### ISSUE TITLE
Requesting support for Australia

### ISSUE THREAD

**Issue by husnainali09** [DurgNomis-drol/mytoyota#181]
Hoping to get support for Australia

**Comment by joro75** [comment]
Hi @husnainali09  ,

I checked the 'MyToyota' page for Australia. It is available on: https://www.toyota.com.au/connected/connect-app
It is referring to the Android 'myToyota Connect' app on https://play.google.com/store/apps/details?id=com.au.toyota.oneapp. 

This however seems to have a different layout, and different settings than the 'MyT' app (https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=en) that this [mytoyota](https://github.com/DurgNomis-drol/mytoyota) library is using. I'm also afraid that the backend toyota servers are also different. 

Did you already try to use the small example program (as shown on https://github.com/DurgNomis-drol/mytoyota ) to retrieve the information of your vehicle? Is that working, or isn't it?

**Comment by DurgNomis-drol** [comment]
Toyota Connected Services is very different for each region. I believe that the system is build by different Toyota partners and therefor it is incompatible with each other. When I set out to build this over a year and a half ago, I thought I could make a global library. But this is not possible as each regions app does not share anything in common with each other.

You can only hope that some one in the future creates a library or you can take the journey yourself 😃

**Comment by joro75** [comment]
Also please see https://github.com/DurgNomis-drol/mytoyota/discussions/207 for a more detailed explanation.
