### ISSUE TITLE
PLZ requesting support for Puerto Rico

### ISSUE THREAD

**Issue by hvrivera** [DurgNomis-drol/mytoyota#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DurgNomis-drol** [comment]
Please try the North American version https://github.com/widewing/ha-toyota-na

**Comment by joro75** [comment]
Also please see https://github.com/DurgNomis-drol/mytoyota/discussions/207 for a more detailed explanation.
