### ISSUE TITLE
Performance problems with API

### ISSUE THREAD

**Issue by Iture** [DurgNomis-drol/mytoyota#204]
Hi
maybe I'm alone with this problem, but since November 29th I've started noticing strange problems. Toyota API often returns HTTP 429 answer on vehicleStatus endpoint. Problem didn't stopped even after implementing strong throttling, and it looks that API has performance problems. In the same time application works correctly, and I'm just wondering if Toyota hasn't changed its API endpoints to new ones with the application (while leaving old ones scaled down for older application instances). Last update for the application was on November 18th. 
Do you have an option to verify traffic generated from the application? I have locked phone :(.

**Comment by joro75** [comment]
Hi @Iture,

You are not the only one. I'm also having problems since November 29th.
I'm receiving: 'ToyotaApiError':'HTTP: 429 - Too Many Requests. Please try again later.'

I already created a [ticket](https://github.com/joro75/Domoticz-Toyota-Plugin/issues/53)  on my own plugin that is using mytoyota, as I was not sure if it applies to mytoyota in general or only my own plugin.

Based on your problem report, I do expect that we are observing the same. I didn't have time yet to further investigate the problem. It could indeed be that toyota has changed to other servers. The strange thing is that the mytoyota app on my phone is still working correctly, and doesn't seem to be influenced. 

There certainly is something going on....

**Comment by joro75** [comment]
The version of the MyT app on my phone as of now is: "Version 4.14.0 (30167)"

**Comment by joro75** [comment]
Your hypothesis seems valid to me, this sounds very plausible. 
I'm also searching on internet fora, if other users are seeing the same problem. Cannot find any clear report yet. 
There however also seems to have been some problem in the last week of October. At that moment my car was not registered anymore, and I had to re-register it in the Toyota MyT App I now understand that more people have had that problem at the end of October. Did you also have to re-register it in the MyT App?

I'm sadly also not able to monitor the network traffic, so I cannot check the address of the servers.

**Comment by joro75** [comment]
I already tried to update the "X-TME-APP-VERSION" to "4.14.0", to determine if it fixes the problem. No, it isn't. 😒

**Comment by Iture** [comment]
It is really strange:
I just generated curl commands ```print ('curl -H "Cookie:%s" -H "uuid:%s" %s' % (headers['Cookie'],self.uuid,url))```
in the controller.request method and they are working flawlessly. Event more - i tried to isssue single request to single endpoint: ```await client.api.get_vehicle_status_legacy_endpoint(vin)``` and got the same 429 error. 
Even tried older versions of httpx, no success
Running out the ideas.

**Comment by Iture** [comment]
I've got something:
- when I'm issuing 100 requests sequentially (from request module) everything works
- when I'm issuing __one__ request using httpx client, got 429
- and the best: making the same 100 request with aiohttp library works

Absolutely no idea why, but t looks that **problem lies somewhere in the httpx module**

**Comment by Iture** [comment]
I've got a solution: set user-agent header. It looks that Toyota introduced some protection mechanism, and discards unknown user-agents. Adding user-agent header (I just set it to the same value as my browser), helped imediately

**Comment by DurgNomis-drol** [comment]
@Iture Awesome job finding out how to fix this!! 🚀 🙇 

Funny enough I actually choose `httpx` back when I started because `aiohttp` didn't work with toyota's servers. 😆

**Comment by DurgNomis-drol** [comment]
It works, new versions have been released! Including a legacy version for the HA integration.

Again, thanks for the detective work @Iture It is much appreciated 🚀
