### ISSUE TITLE
TripEvent interval

### ISSUE THREAD

**Issue by vrachieru** [DurgNomis-drol/mytoyota#238]
Hi,

Are you aware what is the interval between the trip events?
They do not contain a timestamp and I could not figure out what the interval between them is, be it time or distance..
If anyone does know, please share.

Thank you!

**Comment by CM000n** [comment]
We have recently released a beta version for the new API endpoints and will be focussing our work on this in the future.
Please check if your issue still applies to the new version.

**Comment by CM000n** [comment]
With the latest API changes in `mytoyota` >= 1.0 , a `start_time` and an `end_time` are now always returned for trips.
