### ISSUE TITLE
`get_vehicle_status().dashboard.battery_level` is not returning fresh data

### ISSUE THREAD

**Issue by iksunen** [DurgNomis-drol/mytoyota#239]
**Describe the bug**
When the car is charging, `get_vehicle_status().dashboard.battery_level` does not return fresh data, but the data that was fetched when `MyT` app has refreshed charging status from the `Remote Charging` menu by clicking the refresh button (screenshot attached):

<details>
 <summary>Screenshot</summary>
<img src="https://github.com/DurgNomis-drol/mytoyota/assets/139585475/0278370d-ea73-4c52-ba54-a6bd659d7350" width="300">
</details>

Not exactly sure if this falls under a bug or feature request, putting it under bug since to me it sounds like the current behaviour is somewhat misleading.

**To Reproduce**

- Plug the car (Toyota RAV4 PHEV 2022) to charge
- Run mytoyota client with the (cropped) code below:

```python
from mytoyota.client import MyT

client = MyT(username=username, password=password, brand=brand)
await client.login()
vehicle = await client.get_vehicle_status(car)
charging_status = vehicle.dashboard.charging_status # this correctly returns 'charging' status
battery = vehicle.dashboard.battery_level # this will always return the same value while the car is charging
```

As per comment, when battery level is updated using the client, it returns the same value throughout the time that the car is charging.
Currently the only way to get an up-to-date charge value is by opening MyT app, going into `Remote Charging` menu and refreshing the data, which is obviously a blocker for doing automation using the client.

**Expected behavior**
Calling `await client.get_vehicle_status(car).dashboard.battery_level` should return up-to-date value on every call.

---
I meant to intercept the http request that the `MyT` app is performing when the refresh button is clicked, however so far the apk that's rebuilt with client certificates allowed fails on login step. If there's info on what toyota-europe API endpoint is used to refresh the data, it would also be of great help.

Thanks!

**Comment by joro75** [comment]
Thanks for the detailed description of your request. It is clear what you are observing, and I also fully understand the improvement you are suggesting.

The problem at this moment is that we have to find the API endpoint to trigger an update of the status information. 
So we first have to determine this API endpoint, and then we can implement it.

**Comment by manelmg** [comment]
Any update about it?
Thanks

**Comment by CM000n** [comment]
We have recently released a beta version for the new API endpoints and will be focussing our work on this in the future.
Please check if your issue still applies to the new version.

**Comment by GitOldGrumpy** [comment]
Ill take a look at this. I would like the this for myself(so I can decide when to stop charging of my car for the next days travel) although that last time I looked I could not find the correct endpoint, but I did stop looking to concentrate on getting the API in better shape.

**Comment by iksunen** [comment]
Getting the following log prints with PR branch changes when running `simple_client_example.py`:
```bash
/v1/global/remote/electric/realtime-status: {'status': {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}, 'payload': {'appRequestNo': 'fd1e6a67-8ca4-3d30-96d9-b223d0ee19e6', 'returnCode': '000000'}}
/v1/global/remote/refresh-status: Threw Request Failed.  500, {"message": "Internal server error"}.
/v1/global/remote/refresh-climate-status: {'status': {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}, 'payload': {'appRequestNo': '7ac9c710-a0e4-30d2-90b3-84ff52725df7', 'returnCode': '000000'}}
```

And unfortunately the battery level printed is still not up-to-date, i.e. the refresh-status endpoint does not seem to do the trick.

**Comment by manelmg** [comment]
@iksunen please, can you share piece of code to refresh battery level? I am no able to refresh it via python code.

Thanks in advance

**Comment by iksunen** [comment]
@manelmg I used the [`force_update()`](https://github.com/DurgNomis-drol/mytoyota/pull/302/files#diff-8f6d298971718cf37b75ce7902c0859476510361d3208e4fe55ed7784229f586R396) method from @GitOldGrumpy's [PR](https://github.com/DurgNomis-drol/mytoyota/pull/302):

```python
from mytoyota.client import MyT

client = MyT(username=USERNAME, password=PASSWORD)
await client.login()
cars = await client.get_vehicles(metric=True)
for car in cars:
  # calling force_update() before printing car.dashboard.battery_level ensures it has the up-to-date value
  await car.force_update()
  print('Current battery level: {}'.format(car.dashboard.battery_level))
```

I am running my code from the PR branch as it's fine for my project. I think I only needed to do `poetry install` to make it work.
