### ISSUE TITLE
Maintainer Access...

### ISSUE THREAD

**Issue by GitOldGrumpy** [DurgNomis-drol/mytoyota#259]
Hi could someone grant me maintainer access so I can create branches with new work for review? Might be easier than me creating pull requests?

Thanks.

**Comment by GitOldGrumpy** [comment]
Also, what is the plan for adding new features? Create a ticket do the work, get it reviews and merged to master.

**Comment by CM000n** [comment]
Hi, the only one who can currently give you maintainer rights is @GitOldGrumpy 

> Hi could someone grant me maintainer access so I can create branches with new work for review? Might be easier than me creating pull requests?
> 
> Thanks.

Hi, the only one who can currently give you maintainer rights is @GitOldGrumpy

**Comment by CM000n** [comment]
> Also, what is the plan for adding new features? Create a ticket do the work, get it reviews and merged to master.

I don't think a ticket is absolutely necessary. Simply open a new feature or enhancement branch and create a merge request for it.

**Comment by CM000n** [comment]
As Long as you don't have maintainer access, you can still create branches an pull requests from your fork @GitOldGrumpy.
Makes no real big difference in workflow.

Greetings and merry Christmas 🎅🏻

**Comment by CM000n** [comment]
I asked @DurgNomis-drol in the Home Assistant forum again via direct message if he gives you maintainer rights @GitOldGrumpy.
Hopefully he reads the messages there more often 😉

**Comment by DurgNomis-drol** [comment]
If you want to add features you just make a PR with code. If it is big, and you are don't want to do all the coding for it to be turned down, you can open an issue first outlining the idea.

Maintainer rights are normally not something you request to get, but something that is given to you when you provide value to the project overtime. As @CM000n states it does not make a real difference in the workflow if you have it or not. 

You have been added.
