### ISSUE TITLE
SummaryType error if using simple_client_example.py

### ISSUE THREAD

**Issue by dvogt23** [DurgNomis-drol/mytoyota#273]
**Describe the bug**
Getting following error if using `simple_client_example.py`:

```
Traceback (most recent call last):
  File "/home/pi/toyota/simple_client_example.py", line 8, in <module>
    from mytoyota.models.summary import SummaryType
ModuleNotFoundError: No module named 'mytoyota.models.summary'
```

**To Reproduce**
Python 3.9.2

Run: `python simple_client_example.py`

**Comment by CM000n** [comment]
Hello @dvogt23, thank you for reporting.
Unfortunately, I cannot reproduce the error. 😞
Which version of the `mytoyota` package are you using and how did you install it? Directly the latest version from the master of the repo or via pip the latest Pypi release version?

**Comment by dvogt23** [comment]
Hello @CM000n I did it with:
`python -m pip install "mytoyota @ git+https://github.com/DurgNomis-drol/mytoyota@master"`

**Comment by CM000n** [comment]
Did you select the correct Python environment when calling simple_client_example.py?
Sorry if I'm asking such a stupid question, but I really can't reproduce this behavior.

Did you possibly use the `python3` instead of `python` command at some point and got confused?

**Comment by dvogt23** [comment]
Ok, it works with your instructions, seems like smthg wrong with my old env 🤔 

Thanks for your help :))
