### ISSUE TITLE
Inconsistency in statistics summaries

### ISSUE THREAD

**Issue by CM000n** [DurgNomis-drol/mytoyota#281]
I am currently in the process of adapting the Home Assistant integration to the new `mytoyota` version.
I noticed that the statistics summaries are inconsistent.
According to the current date (08 January 2024), the monthly and annual statistics should be the same. However, for the same period from 01.01 to 08.01.2024 I get different values for month (e.g. 90km distance) and year (e.g. 179km distance).

![Screenshot_20240108-172537](https://github.com/DurgNomis-drol/mytoyota/assets/7945681/f20886d4-dcb1-49b7-bc9e-79bc77b01485)

**Comment by CM000n** [comment]
Fyi @GitOldGrumpy :wink:

**Comment by GitOldGrumpy** [comment]
Ill take a look later, if I can find a few spare minutes.

**Comment by GitOldGrumpy** [comment]
The code always expects there to be multiple months and it doesn't work anyway as the first month is always added twice.
