### ISSUE TITLE
Show inspections and service history

### ISSUE THREAD

**Issue by vwtuner** [DurgNomis-drol/mytoyota#311]
Wenn sie Zeit und Lust haben können sie noch die Inspektion mit einfügen in HA.

vielen Dank

**Comment by CM000n** [comment]
Hallo @vwtuner, vielen Dank für deine Anfrage. Ich werde mir das einmal anschauen. 😊 
Übrigens: Auch wenn ich selbst Deutscher bin: Die meisten Leute hier sind es nicht. 😉  
Daher werde ich mir erlauben, einige deiner Sachen ins englische zu übersetzten.

---

Hello @vwtuner, thank you for your enquiry. I will have a look at it. 😊 
By the way: Even though I'm German myself: Most people here are not. 😉  
I will therefore take the liberty of translating some of your things into English.

**Comment by vwtuner** [comment]
Ok thank you😊

**Comment by vwtuner** [comment]
What do I have to do to see inspection?
reinstall?

**Comment by CM000n** [comment]
This belongs only to the `mytoyota` python lib and not to the home assistant integration!
When you follow this instructions you should already be able to see your latest service: https://github.com/DurgNomis-drol/mytoyota?tab=readme-ov-file#usage
Feel free to test it 😊
