### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by RCG-SW** [DurgNomis-drol/mytoyota#339]
Trying to authenticate I get 
![image](https://github.com/DurgNomis-drol/mytoyota/assets/64915214/4c1848dc-e805-4230-b2a6-7ceef2f067bb)
I get a 400 Bad request

**Comment by CM000n** [comment]
Sorry to say it so directly, but such an issue description is really not very helpful.
Can you give us a little more information? 
How did you try to log in (directly via the python lib or via a third party app that uses it), which vehicle do you have, is your vehicle already migrated to the current MyToyota API, do you see any other errors when you activate logging...

**Comment by CM000n** [comment]
Closed due to inactivity and lack of information
